name: llms
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - ansi2html=1.9.2
  - anyio=4.7.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - babel=2.16.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.8
  - clickhouse-connect=0.8.11
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart_win-64=12.6.77
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cudnn=9.3.0.75
  - cycler=0.12.1
  - dash=2.18.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - double-conversion=3.3.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - faiss=1.9.0
  - fastapi=0.115.6
  - fastapi-cli=0.0.7
  - filelock=3.16.1
  - flask=3.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hnswlib=0.8.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - huggingface_hub=0.26.5
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.2.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-dash=0.4.2
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.23
  - libevent=2.1.12
  - libexpat=2.6.4
  - libfaiss=1.9.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libparquet=18.1.0
  - libpng=1.6.44
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsentencepiece=0.2.0
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libuv=1.49.2
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4=4.3.3
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - monotonic=1.6
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - posthog=3.6.5
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pydantic=2.10.4
  - pydantic-core=2.27.2
  - pygments=2.18.0
  - pyparsing=3.2.1
  - pyreadline3=3.5.4
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-duckdb=1.1.3
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=307
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.8.1
  - re2=2024.07.02
  - referencing=0.35.1
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - scikit-learn=1.6.0
  - send2trash=1.8.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=75.6.0
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - starlette=0.41.3
  - sympy=1.13.3
  - tbb=2021.13.0
  - tenacity=9.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - watchfiles=1.0.3
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=14.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.2.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.2
      - altair==5.5.0
      - anthropic==0.42.0
      - asgiref==3.8.1
      - bcrypt==4.2.1
      - bitsandbytes==0.45.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.20
      - dataclasses-json==0.6.7
      - datasets==3.2.0
      - deprecated==1.2.15
      - dill==0.3.8
      - distro==1.9.0
      - durationpy==0.9
      - faiss-cpu==1.9.0.post1
      - feedparser==6.0.11
      - ffmpy==0.5.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gensim==4.3.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.157.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - gradio==5.9.1
      - gradio-client==1.5.2
      - greenlet==3.1.1
      - grpcio==1.68.1
      - grpcio-status==1.68.1
      - grpclib==0.4.7
      - httplib2==0.22.0
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - jiter==0.8.2
      - jsonpatch==1.33
      - kubernetes==31.0.0
      - langchain==0.3.14
      - langchain-chroma==0.1.4
      - langchain-community==0.3.14
      - langchain-core==0.3.29
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.4
      - langsmith==0.2.7
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - marshmallow==3.23.2
      - mmh3==5.0.1
      - modal==0.71.0
      - more-itertools==10.5.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - narwhals==1.20.1
      - numba==0.60.0
      - oauthlib==3.2.2
      - ollama==0.4.5
      - onnxruntime==1.20.1
      - openai==1.59.3
      - openai-whisper==20240930
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.13
      - propcache==0.2.1
      - proto-plus==1.25.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyaudio==0.2.14
      - pydantic-settings==2.7.1
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pypdf2==3.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytube==15.0.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - ruff==0.8.5
      - safehttpx==0.1.6
      - safetensors==0.5.0
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentence-transformers==3.3.1
      - sgmllib3k==1.0.0
      - sigtools==4.0.1
      - smart-open==7.1.0
      - smmap==5.0.2
      - speechrecognition==3.13.0
      - speedtest-cli==2.1.3
      - sqlalchemy==2.0.36
      - srt==3.5.3
      - streamlit==1.41.1
      - synchronicity==0.9.8
      - tiktoken==0.8.0
      - toml==0.10.2
      - tomlkit==0.13.2
      - transformers==4.47.1
      - twilio==9.4.1
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing-inspect==0.9.0
      - uritemplate==4.1.1
      - vosk==0.3.45
      - watchdog==6.0.0
      - wrapt==1.17.0
      - xxhash==3.5.0
      - yarl==1.18.3